action: save # train or test
name: features_rgb
modality: ["RGB"] # modality used
split: train #or test
features_path: [RGB_preprocessed]

save:
  num_clips: 5
  dense_sampling:
    RGB: ??
  num_frames_per_clip:
    RGB: ??

dataset:
  annotations_path: labels_AN/labels_S04
  shift: S04-S04
  workers: 4
  stride: 2
  resolution: 224
  num_classes: 8
  RGB:
    data_path: action-net/frames
    tmpl: "frame_{:010d}.jpg"
  Event:
    rgb4e: 6

# these are the action recognition models for each modality
models:
  RGB:
    model: I3D
    dropout: 0.5
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
    weight_i3d_rgb: './pretrained_i3d/rgb_imagenet.pt'



