action: train # train or test
name: training multimodal # name of the experiment needed for the logs
modality: ["MID_FUSION"] # modality used
total_batch: 128 # total batch size if training is done with gradient accumulation
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
logname: null # name of the logs
models_dir: saved_models # directory containing all the models
resume_from: null


train:
  num_iter: 800 # number of training iterations with total_batch size
  lr_steps: 500 # steps before reducing learning rate
  eval_freq: 50 # evaluation frequency
  num_clips: 5 # clips adopted in training
  spectogram: False
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in training for each modality
    RGB: 10

test:
  num_clips: 5 # number of clips in testing
  dense_sampling: # sampling version adopted in test for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in test for each modality
    RGB: 10

dataset:
  annotations_path: labels_AN/labels_S04 # path for the annotations data
  shift: S04-S04 # shifts of the dataset
  workers: 4 # number of workers for the dataloader
  stride: 2 # stride in case of dense sampling
  resolution: 224 # input resolution to the model
  num_classes: 20
  MID_FUSION:
    data_path: Fusion_preprocessed # folder to pkl data
    tmpl: "img_{:010d}.jpg" # format of RGB filenames
    features_name: midlevel_feat # name of the pkl file
  Event: # not neeeded for the project
    rgb4e: 6

# these are the action recognition models for each modality
models:
  MID_FUSION:
    model: FusionClassifier 
    normalize: False
    kwargs: {}
    lr_steps: 500
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7